# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Bundle App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
      # Download the Databricks CLI.1
      # See https://github.com/databricks/setup-cli
      
    - uses: databricks/setup-cli@main

    # Deploy the bundle to the "qa" target as defined
    # in the bundle's settings file.
    - run: databricks bundle deploy
      working-directory: .
      env:
        DATABRICKS_TOKEN: dapi3dd847d7cc73e2aa439f2cc9ea3897cc       
        DATABRICKS_BUNDLE_ENV: development1


  
